module.exports = {
  env: {
    SERVER: process.env.SERVER,
    REDIS:process.env.REDIS_URL,
    NEXT_REDI_TOKEN:process.env.NEXT_REDI_TOKEN,
NEXT_PUBLIC_AUTH0_CLIENT_ID:process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID,
NEXT_PUBLIC_AUTH0_DOMAIN:process.env.NEXT_PUBLIC_AUTH0_DOMAIN,
NEXT_PUBLIC_AUTH0_ADMIN_EMAIL:process.env.NEXT_PUBLIC_AUTH0_ADMIN_EMAIL,
NEXT_CONTENTFUL_SPACE_ID:process.env.NEXT_CONTENTFUL_SPACE_ID,
NEXT_CONTENTFUL_ACCESS_TOKEN:process.env.NEXT_CONTENTFUL_ACCESS_TOKEN,
NEXT_GOOGLE_MAPS_API_KEY:process.env.NEXT_GOOGLE_MAPS_API_KEY,
MAILCHIMP_API_KEY:process.env.MAILCHIMP_API_KEY,
MAILCHIMP_API_SERVER:process.env.MAILCHIMP_API_SERVER,
MAILCHIMP_AUDIENCE_ID:process.env.MAILCHIMP_AUDIENCE_ID
  },
  images:{
    domains:['images.ctfassets.net']
  },

 
};

